using DevNexus.Shared.Constants;
using DevNexus.Shared.DTOs;
using DevNexus.Infrastructure.Services.Parsing;
using Microsoft.Extensions.Logging;
using Microsoft.KernelMemory;
using System.Diagnostics;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

namespace DevNexus.Infrastructure.Services.KnowledgeBase;

/// <summary>
/// 知识库服务 - 基于 Kernel Memory 实现。
/// </summary>
public class KnowledgeBaseService : IKnowledgeBaseService
{
    private const string DefaultIndex = "devnexus-knowledge";

    private static class TagKeys
    {
        public const string UserId = "userId";
        public const string FileId = "fileId";
        public const string FileName = "fileName";
        public const string ChunkId = "chunkId";
        public const string ChunkType = "chunkType";
        public const string SheetName = "sheetName";
        public const string RowStart = "rowStart";
        public const string RowEnd = "rowEnd";
        public const string RowCount = "rowCount";
        public const string ColumnCount = "columnCount";
        public const string HeadersText = "headersText";
        public const string ChunkLabel = "chunkLabel";
        public const string PiiRedacted = "piiRedacted";
        public const string PiiRedactionCount = "piiRedactionCount";
    }

    private static class PiiMetadataKeys
    {
        public const string PiiRedacted = "PIIRedacted";
        public const string PiiRedactionCount = "PIIRedactionCount";
    }

    private static readonly Regex EmailRegex = new(
        @"(?<![\w.-])[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}(?![\w.-])",
        RegexOptions.Compiled | RegexOptions.IgnoreCase);

    private static readonly Regex PhoneRegex = new(
        @"(?<!\d)(?:\+?\d{1,3}[-\s]?)?(?:1[3-9]\d{9}|\d{3}[-\s]?\d{3,4}[-\s]?\d{4})(?!\d)",
        RegexOptions.Compiled);

    private static readonly Regex IdRegex = new(
        @"(?<![A-Za-z0-9])(?:\d{15}|\d{17}[\dXx]|[A-Z]{2}\d{6,12})(?![A-Za-z0-9])",
        RegexOptions.Compiled);

    private readonly ILogger<KnowledgeBaseService> _logger;
    private readonly IKernelMemory _kernelMemory;

    private sealed class PiiRedactionResult
    {
        public string Text { get; init; } = string.Empty;
        public int RedactionCount { get; init; }
    }

    public KnowledgeBaseService(
        ILogger<KnowledgeBaseService> logger,
        IKernelMemory kernelMemory)
    {
        _logger = logger;
        _kernelMemory = kernelMemory ?? throw new ArgumentNullException(nameof(kernelMemory));
    }

    public async Task UpsertDocumentAsync(SmartDocument document, CancellationToken cancellationToken = default)
    {
        await UpsertDocumentAsync(document, Guid.Empty, cancellationToken);
    }

    public async Task UpsertDocumentAsync(SmartDocument document, Guid userId, CancellationToken cancellationToken = default)
    {
        _logger.LogDebug(
            "Upserting document to Knowledge Base: {FileName} ({Id}) | UserId={UserId}",
            document.FileName,
            document.FileId,
            userId);

        if (document.Chunks == null || !document.Chunks.Any())
        {
            if (document.Content is TextDocumentContent textContent && !string.IsNullOrWhiteSpace(textContent.Text))
            {
                _logger.LogInformation("Document has no chunks. Auto-generating chunk from TextDocumentContent.");
                document.Chunks = new List<SmartChunk>
                {
                    new()
                    {
                        Id = Guid.NewGuid().ToString(),
                        Type = ChunkType.Text,
                        Content = textContent.Text,
                        Metadata = new Dictionary<string, object>
                        {
                            ["Source"] = "AutoGeneratedFromContent",
                            ["PageCount"] = textContent.PageCount
                        }
                    }
                };
            }
            else
            {
                _logger.LogWarning("Document has no chunks and no suitable content to index.");
                return;
            }
        }

        var indexStopwatch = Stopwatch.StartNew();
        int indexedChunkCount = 0;
        int redactedChunkCount = 0;
        int totalRedactionCount = 0;

        try
        {
            foreach (var chunk in document.Chunks)
            {
                var textContent = BuildTextContent(chunk);
                var redacted = RedactPii(textContent);

                if (redacted.RedactionCount > 0)
                {
                    redactedChunkCount++;
                    totalRedactionCount += redacted.RedactionCount;
                    chunk.Metadata[PiiMetadataKeys.PiiRedacted] = true;
                    chunk.Metadata[PiiMetadataKeys.PiiRedactionCount] = redacted.RedactionCount;
                }

                await _kernelMemory.ImportTextAsync(
                    text: redacted.Text,
                    documentId: $"{document.FileId}_{chunk.Id}",
                    index: DefaultIndex,
                    tags: BuildTags(document, userId, chunk, redacted.RedactionCount),
                    cancellationToken: cancellationToken);

                indexedChunkCount++;
            }

            if (totalRedactionCount > 0)
            {
                document.Metadata[PiiMetadataKeys.PiiRedacted] = true;
                document.Metadata[PiiMetadataKeys.PiiRedactionCount] = totalRedactionCount;
            }

            _logger.LogInformation(
                "[RAG.Index] Indexed document | FileId={FileId} UserId={UserId} Chunks={Chunks} RedactedChunks={RedactedChunks} PiiRedactions={Redactions} DurationMs={DurationMs}",
                document.FileId,
                userId,
                indexedChunkCount,
                redactedChunkCount,
                totalRedactionCount,
                indexStopwatch.ElapsedMilliseconds);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to upsert document {FileId}", document.FileId);
            throw;
        }
    }

    public async Task<List<SmartChunk>> SearchAsync(string query, int limit = 5, double minScore = 0.7)
    {
        return await SearchAsync(query, Guid.Empty, limit, minScore);
    }

    public async Task<List<SmartChunk>> SearchAsync(
        string query,
        Guid userId,
        int limit = 5,
        double minScore = 0.7,
        CancellationToken cancellationToken = default)
    {
        try
        {
            var filters = new List<MemoryFilter>();
            if (userId != Guid.Empty)
            {
                filters.Add(MemoryFilters.ByTag(TagKeys.UserId, userId.ToString()));
                _logger.LogDebug("[RAG] Searching with userId filter | UserId={UserId} Query={Query}", userId, query);
            }

            var searchStopwatch = Stopwatch.StartNew();
            var searchResult = await _kernelMemory.SearchAsync(
                query: query,
                index: DefaultIndex,
                filters: filters,
                limit: limit,
                minRelevance: minScore,
                cancellationToken: cancellationToken);

            var results = searchResult.Results
                .SelectMany(result => result.Partitions.Select(partition => new { Result = result, Partition = partition }))
                .Select(item => new SmartChunk
                {
                    Id = item.Partition.PartitionNumber.ToString(),
                    Content = item.Partition.Text,
                    Type = ParseChunkType(GetTagValue(item.Partition.Tags, TagKeys.ChunkType)),
                    Embedding = null,
                    Metadata = BuildSearchMetadata(item.Result, item.Partition)
                })
                .ToList();

            _logger.LogDebug(
                "[RAG] Search completed | UserId={UserId} Query={Query} Results={Count} DurationMs={DurationMs}",
                userId,
                query.Length > 50 ? query[..50] + "..." : query,
                results.Count,
                searchStopwatch.ElapsedMilliseconds);

            return results;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "[RAG] Search failed | UserId={UserId}", userId);
            return new List<SmartChunk>();
        }
    }

    private static TagCollection BuildTags(
        SmartDocument document,
        Guid userId,
        SmartChunk chunk,
        int piiRedactionCount)
    {
        var tags = new TagCollection
        {
            { TagKeys.UserId, userId.ToString() },
            { TagKeys.FileId, document.FileId },
            { TagKeys.FileName, document.FileName },
            { TagKeys.ChunkId, chunk.Id },
            { TagKeys.ChunkType, chunk.Type.ToString() }
        };

        AddTag(tags, TagKeys.SheetName, chunk.Metadata, TableChunkMetadataKeys.SheetName);
        AddTag(tags, TagKeys.RowStart, chunk.Metadata, TableChunkMetadataKeys.RowStart);
        AddTag(tags, TagKeys.RowEnd, chunk.Metadata, TableChunkMetadataKeys.RowEnd);
        AddTag(tags, TagKeys.RowCount, chunk.Metadata, TableChunkMetadataKeys.RowCount);
        AddTag(tags, TagKeys.ColumnCount, chunk.Metadata, TableChunkMetadataKeys.ColumnCount);
        AddTag(tags, TagKeys.HeadersText, chunk.Metadata, TableChunkMetadataKeys.HeadersText);
        AddTag(tags, TagKeys.ChunkLabel, chunk.Metadata, TableChunkMetadataKeys.ChunkLabel);

        if (piiRedactionCount > 0)
        {
            tags.Add(TagKeys.PiiRedacted, "true");
            tags.Add(TagKeys.PiiRedactionCount, piiRedactionCount.ToString());
        }

        return tags;
    }

    private static void AddTag(TagCollection tags, string tagKey, Dictionary<string, object> metadata, string metadataKey)
    {
        if (!metadata.TryGetValue(metadataKey, out var value) || value == null)
        {
            return;
        }

        var stringValue = value switch
        {
            string s => s,
            JsonElement element => element.ToString(),
            _ => value.ToString()
        };

        if (!string.IsNullOrWhiteSpace(stringValue))
        {
            tags.Add(tagKey, stringValue);
        }
    }

    private static Dictionary<string, object> BuildSearchMetadata(Citation citation, Citation.Partition partition)
    {
        var metadata = new Dictionary<string, object>
        {
            [SearchResultMetadataKeys.Score] = partition.Relevance,
            [SearchResultMetadataKeys.FileName] = citation.SourceName ?? "Unknown",
            [SearchResultMetadataKeys.DocumentId] = citation.DocumentId
        };

        AddSearchMetadata(metadata, partition.Tags, TagKeys.SheetName, TableChunkMetadataKeys.SheetName);
        AddSearchMetadata(metadata, partition.Tags, TagKeys.RowStart, TableChunkMetadataKeys.RowStart);
        AddSearchMetadata(metadata, partition.Tags, TagKeys.RowEnd, TableChunkMetadataKeys.RowEnd);
        AddSearchMetadata(metadata, partition.Tags, TagKeys.RowCount, TableChunkMetadataKeys.RowCount);
        AddSearchMetadata(metadata, partition.Tags, TagKeys.ColumnCount, TableChunkMetadataKeys.ColumnCount);
        AddSearchMetadata(metadata, partition.Tags, TagKeys.HeadersText, TableChunkMetadataKeys.HeadersText);
        AddSearchMetadata(metadata, partition.Tags, TagKeys.ChunkLabel, TableChunkMetadataKeys.ChunkLabel);
        AddSearchMetadata(metadata, partition.Tags, TagKeys.PiiRedacted, PiiMetadataKeys.PiiRedacted);
        AddSearchMetadata(metadata, partition.Tags, TagKeys.PiiRedactionCount, PiiMetadataKeys.PiiRedactionCount);

        return metadata;
    }

    private static void AddSearchMetadata(
        Dictionary<string, object> metadata,
        TagCollection? tags,
        string tagKey,
        string metadataKey)
    {
        var value = GetTagValue(tags, tagKey);
        if (!string.IsNullOrWhiteSpace(value))
        {
            metadata[metadataKey] = value;
        }
    }

    private static PiiRedactionResult RedactPii(string text)
    {
        int count = 0;
        var emailReplacement = ReplaceWithCount(text, EmailRegex, "[REDACTED_EMAIL]");
        count += emailReplacement.Count;
        var phoneReplacement = ReplaceWithCount(emailReplacement.Text, PhoneRegex, "[REDACTED_PHONE]");
        count += phoneReplacement.Count;
        var idReplacement = ReplaceWithCount(phoneReplacement.Text, IdRegex, "[REDACTED_ID]");
        count += idReplacement.Count;

        return new PiiRedactionResult
        {
            Text = idReplacement.Text,
            RedactionCount = count
        };
    }

    private static (string Text, int Count) ReplaceWithCount(string input, Regex regex, string replacement)
    {
        int localCount = 0;
        var replaced = regex.Replace(input, _ =>
        {
            localCount++;
            return replacement;
        });

        return (replaced, localCount);
    }

    private static string? GetTagValue(TagCollection? tags, string key)
    {
        if (tags == null)
        {
            return null;
        }

        return tags.TryGetValue(key, out var values) && values.Count > 0
            ? values.First()
            : null;
    }

    private static ChunkType ParseChunkType(string? typeString)
    {
        if (string.IsNullOrEmpty(typeString))
        {
            return ChunkType.Text;
        }

        return Enum.TryParse<ChunkType>(typeString, out var chunkType)
            ? chunkType
            : ChunkType.Text;
    }

    private static string BuildTextContent(SmartChunk chunk)
    {
        var builder = new StringBuilder();
        builder.AppendLine($"Type: {chunk.Type}");

        if (chunk.Type == ChunkType.Table)
        {
            AppendChunkMetadataLine(builder, "Sheet", chunk.Metadata, TableChunkMetadataKeys.SheetName);
            AppendChunkMetadataLine(builder, "Rows", chunk.Metadata, TableChunkMetadataKeys.RowStart, TableChunkMetadataKeys.RowEnd);
            AppendChunkMetadataLine(builder, "Headers", chunk.Metadata, TableChunkMetadataKeys.HeadersText);
        }

        builder.AppendLine("Content:");
        builder.AppendLine(chunk.Content);

        if (!string.IsNullOrEmpty(chunk.StructuredData))
        {
            builder.AppendLine("Data:");
            builder.AppendLine(chunk.StructuredData);
        }

        return builder.ToString();
    }

    private static void AppendChunkMetadataLine(
        StringBuilder builder,
        string label,
        Dictionary<string, object> metadata,
        string key)
    {
        if (!metadata.TryGetValue(key, out var value) || value == null)
        {
            return;
        }

        builder.AppendLine($"{label}: {value}");
    }

    private static void AppendChunkMetadataLine(
        StringBuilder builder,
        string label,
        Dictionary<string, object> metadata,
        string startKey,
        string endKey)
    {
        if (!metadata.TryGetValue(startKey, out var startValue) || startValue == null)
        {
            return;
        }

        if (!metadata.TryGetValue(endKey, out var endValue) || endValue == null)
        {
            builder.AppendLine($"{label}: {startValue}");
            return;
        }

        builder.AppendLine($"{label}: {startValue}-{endValue}");
    }
}
