<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>c5958a2d-8b48-4db6-8f2c-216e40b8114d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" PrivateAssets="all" />
    <PackageReference Include="Blazored.LocalStorage" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="DevNexus.Client.Shared.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DevNexus.Client.Shared\DevNexus.Client.Shared.csproj" />
    <ProjectReference Include="..\..\common\DevNexus.Shared\DevNexus.Shared.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <DevNexusHostPageStyleSheet>DevNexus.Client.Web.styles.css</DevNexusHostPageStyleSheet>
    <DevNexusHostPageBlazorScript>blazor.webassembly.js</DevNexusHostPageBlazorScript>
    <DevNexusHostPageIconLinks>&lt;link rel="icon" type="image/svg+xml" href="favicon.svg" /&gt;&#x0A;    &lt;link rel="apple-touch-icon" href="icon-192.svg" /&gt;</DevNexusHostPageIconLinks>
  </PropertyGroup>

  <Import Project="..\DevNexus.Client.Shared\build\DevNexus.Client.HostPage.targets" />


</Project>
