using DevNexus.Domain.Abstractions;
using DevNexus.Domain.Entities;
using DevNexus.Domain.Models;
using DevNexus.Infrastructure.Models;
using DevNexus.Shared.Enums;

namespace DevNexus.Infrastructure.Services.Files;

internal static class FileTaskOutputPublisher
{
    public static async Task<List<Guid>> PublishGeneratedFilesAsync(
        ApplicationDbContext dbContext,
        FileTask task,
        Guid userId,
        IReadOnlyCollection<string> generatedFiles,
        FileOutputValidationResult validationResult,
        bool fallbackUsed,
        string? runnerUsed,
        IFileStorageService storageService,
        CancellationToken cancellationToken)
    {
        var outputAssetIds = new List<Guid>();
        var validationLookup = validationResult.Items.ToDictionary(item => item.FilePath, item => item, StringComparer.OrdinalIgnoreCase);

        foreach (var generatedFilePath in generatedFiles)
        {
            var uploadedFileUrl = await UploadGeneratedFileAsync(task, userId, generatedFilePath, storageService);
            var fileInfo = new FileInfo(generatedFilePath);
            var extension = fileInfo.Extension;
            var assetId = Guid.NewGuid();
            var versionId = Guid.NewGuid();
            var now = DateTime.UtcNow;
            var objectKey = BuildOutputObjectKey(userId, task, fileInfo.Name);
            var validationItem = validationLookup.GetValueOrDefault(generatedFilePath);

            var asset = new FileAsset
            {
                Id = assetId,
                SessionId = task.SessionId,
                CurrentVersionId = versionId,
                OriginalFileName = fileInfo.Name,
                Extension = extension,
                ContentType = GetContentType(extension),
                StorageProvider = storageService.Provider,
                FileUrl = uploadedFileUrl,
                ObjectKey = objectKey,
                SizeBytes = fileInfo.Length,
                Status = FileAssetStatus.Ready,
                SourceType = "file-task-output",
                CreatedAt = now,
                UpdatedAt = now,
                CreatedBy = userId,
                UpdatedBy = userId,
                Metadata = new Dictionary<string, object>
                {
                    ["generatedByTaskId"] = task.Id,
                    ["generatedFilePath"] = generatedFilePath,
                    ["taskType"] = task.TaskType,
                    ["validationCategory"] = validationItem?.Category ?? "generic",
                    ["validationSummary"] = validationItem?.Summary ?? validationResult.Summary,
                    ["executionMode"] = fallbackUsed ? "fallback-summary" : "runner",
                    ["runnerUsed"] = runnerUsed ?? string.Empty
                }
            };

            var version = new FileVersion
            {
                Id = versionId,
                FileAssetId = assetId,
                VersionNumber = 1,
                ObjectKey = objectKey,
                FileUrl = uploadedFileUrl,
                SizeBytes = fileInfo.Length,
                GeneratedByTaskId = task.Id,
                ChangeSummary = "Generated by file task execution",
                CreatedAt = now,
                UpdatedAt = now,
                CreatedBy = userId,
                UpdatedBy = userId
            };

            dbContext.FileAssets.Add(asset);
            dbContext.FileVersions.Add(version);
            outputAssetIds.Add(asset.Id);
        }

        await dbContext.SaveChangesAsync(cancellationToken);
        return outputAssetIds;
    }

    private static async Task<string> UploadGeneratedFileAsync(
        FileTask task,
        Guid userId,
        string generatedFilePath,
        IFileStorageService storageService)
    {
        await using var stream = File.OpenRead(generatedFilePath);
        var objectKey = BuildOutputObjectKey(userId, task, Path.GetFileName(generatedFilePath));
        var contentType = GetContentType(Path.GetExtension(generatedFilePath));

        return await storageService.UploadFileAsync(stream, objectKey, contentType);
    }

    private static string BuildOutputObjectKey(Guid userId, FileTask task, string fileName)
    {
        var sessionSegment = task.SessionId?.ToString("N") ?? "orphan-session";
        var safeFileName = SanitizeFileName(fileName);
        return $"outputs/{userId:N}/{sessionSegment}/{task.Id:N}/{safeFileName}";
    }

    private static string GetContentType(string extension)
    {
        return extension.ToLowerInvariant() switch
        {
            ".md" => "text/markdown",
            ".txt" => "text/plain",
            ".json" => "application/json",
            ".zip" => "application/zip",
            ".csv" => "text/csv",
            ".xlsx" => "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            ".xls" => "application/vnd.ms-excel",
            _ => "application/octet-stream"
        };
    }

    private static string SanitizeFileName(string fileName)
    {
        var invalidChars = Path.GetInvalidFileNameChars();
        var sanitized = new string(fileName.Select(ch => invalidChars.Contains(ch) ? '_' : ch).ToArray());
        return string.IsNullOrWhiteSpace(sanitized) ? "unnamed-file" : sanitized;
    }
}
